---
title: "Introducing the Circuity database management system"
author: "Paul Billing-Ross"
date: "2025-12-11"
categories: [introduction]
---
# Introduction
The Circuity database management software is available for download [from PyPI](https://pypi.org/project/circuitydatabase) for use on a local computer or for use online through [Circuity Live](https://circuity-database.uw.r.appspot.com/).

# How does Circuity organize data?
Circuity is designed to handle data organized as a matrix or table such as a comma separated values file that can be imported into a tool such as Microsoft Excel or Google Sheets. An example of National Football League roster data that can be imported into a Circuity database and queried can be found [here](https://drive.google.com/drive/folders/1xhA3-Pg-acR1cj97urgKJ0oo7NrLd-GV).

## Importing data
Importing data into Circuity involves transforming data from a matrix into an index of word locations and a dictionary of columns where each column contains references to words or numerical values.

# Features
| Feature | Description | Competitors |
| --- | --- | --- |
| Python-native | Circuity is implemented entirely in the Python programming language and can be installed used PyPI and used without additional software or setup. | | [ZODB](https://zodb.org/en/latest/index.html) |
| Functional | The logic of Circuity is implemented entirely with functions as opposed to being object-oriented. | |
| Data stored as Python-native data structures | Data are  stored in the basic [Python data structures](https://docs.python.org/3/tutorial/datastructures.html) of lists and dictionaries as opposed to custom objects. | |
| Data stored in memory | Data is stored in memory as lists and dictionaries. | [Many](https://en.wikipedia.org/wiki/List_of_in-memory_databases) |
| Analytical or read-only | It is designed to perform operations on static data rather than by supporting write or change operations. | Google BigQuery, Amazon Athena |
| Queryable using only words present in the data | Circuity relies on word matching to find query results. There are no special words or query language syntax (such as [SQL](https://en.wikipedia.org/wiki/SQL) or [Cypher](https://neo4j.com/docs/getting-started/cypher/)) required for searching. This is due to the design of the search algorithm structure of the database and does not rely on any machine learning approaches to transforming natural language into query language. | |
| All words are stored in a central index | Circuity treats data as words or number where a word is defined as a contiguous set of symbols with at least one non-numerical symbol and a number is a contiguous set of numbers with an optional decimal. | |
| Data organized by column | | Examples from [Expert Insights](https://expertinsights.com/data-management/the-top-columnar-databases) |

# Circuity logic walkthrough
## Load Python dependencies
```{python}
import circuitydatabase as circuity
```

## Initializing the database
Initializing the database creates (3) data structures. The first structure is what I call the index.The index is a list of dictionaries where a dictionary is a set of key-value pairs. Each dictionary contains (2) key-value pairs: the name of the word and all the locations where that word occurs in the database.

The second data structure is a dictionary that describes the position that each word occurs at in the index which I call the word positions dictionary. I use the word positions dictionary to lookup the location of words in the index. When I initialize the database it is populated with the information for a single word: "index" which occurs at the zero index of the index itself. 

I return both of these data structures in a third dictionary of (2) items where the keys are `index_list` for the index and `word_positions` for the word positions dictionary.

```{python}
database = circuity.initialize_database()
database
```

I can look at the index and word positions dictionary separately using their dictionary keys.
```{python}
database['index_list']
```

```{python}
database['word_positions']
```

## Importing data
Here I have created a comma separated values file containing contact information for several people that I will load into the database that I just created using the Circuity `import_comma_separated_values()` function. This function will update the index and word positions dictionary to include all of the data in the `contacts.csv` file.

```{python}
csv_file_path = 'contacts.csv'
database = circuity.import_comma_separated_values(database, csv_file_path)
database.keys()
```

When I pass the `database` dictionary to the `import_comma_separated_values` function it returns an updated version of the database with (2) additional data structures: `column_names` and `metadata_column_dictionary`. The `column_names` key points to a list of all the names of the columns or headers in the table I just imported. I generate this list in order to better understand what data is available for querying.
```{python}
database['column_names']
```

The `metadata_column_dictionary` mirrors the original tabular data structure except all the words have been replaced with index references. This can serve as a sort of anonymized version of my data structure that can be translated back into words using the index. All of the columns containing numerical values remain unchanged.
```{python}
database['metadata_column_dictionary']
```

They keys of the `metadata_column_dictionary` correspond to the original column names. Each column name includes the table name as the first element which is why all of these keys start with the same number.
```{python}
metadata_column_dictionary = database['metadata_column_dictionary']
column_keys = list(metadata_column_dictionary.keys())
column_keys
```

A column key of `(1, 2, 3)` can be translated back into a natural language name by mapping each number in the key to the word stored at that position in the index.
```{python}
index_list = database['index_list']

column_key = column_keys[0]
column_words = [index_list[position]['word'] for position in column_key]
column_name = " ".join(column_words)
print(f"Column key: {column_key}. Column name: '{column_name}'.")
```

The values in each cell of the of the column can be translated back into words in the same way.
```{python}
metadata_column_values = list(metadata_column_dictionary.values())
example_cell_value = metadata_column_values[0][1]
example_cell_value
```

Circuity checks whether the value of a cell is a numerical type or a dictionary before returning any query results. If it is a dictionary then the program will transform it into a word.
```{python}
example_cell_words = [index_list[position]['word'] for position in example_cell_value['positions']]
example_cell_words
```

## Querying the database
Circuity is designed to support unstructured natural language queries. Users provide keywords in any order to retrieve the results they want. If the word is present in a column cell then Circuity will treat is as an independent variable or static value. If it is found in the column header then Circuity treats it as a dependent variable and will try to return the cell in that column that is most closely aligned with the column positions of the surrounding words in the query phrase.

Circuity measures the proximity of adjoining words in a query phrase using a boolean metric that determines whether the words are in the same row or different rows in order to prioritize results where all of the values occur in the same row.

### Transforming query words into column locations
The first step in processing a query is to transform it from words to column locations. Because the indexing of each column starts with zero any word at position zero is in a column header.
```{python}
query = "ian age"
word_positions = database['word_positions']

query_word_locations_list = circuity.get_query_word_column_locations(
                                                                     query,
                                                                     index_list,
                                                                     word_positions)
query_word_locations_list
```

