---
title: "Player database: example queries"
author: "Paul Billing-Ross"
date: "2025-11-20"
categories: [example,query]
---
# Introduction
Now that I have packaged Circuity Database and uploaded it to PyPI I can import it as a Python dependency and use it programmatically.

# Functions
## Load dependencies
```{python}
#| code-fold: true

# Circuity database
import circuitydatabase as circuity

# Logging
import logging

# Check version
import sys

# Manipulate files
import os
from pathlib import Path
# Read comma separated values file
import csv
# Manipulate the database structures
import json

# Manipulate lists
import random
import itertools
from operator import itemgetter
```

## Check Python version
```{python}
print(sys.version)
```

# Initialize database
## Create database structures
```{python}
csv_file_path = 'jaguars-offensive-players.csv'
```

## Populate database
```{python}
database = circuity.initialize_database()
database = circuity.import_comma_separated_values(database, csv_file_path)
print(database['index_list'])
```

# Example queries
```{python}
#logging.basicConfig(level=logging.DEBUG)
```

### Get the height values of a player.
```{python}
query = 'trevor lawrence height'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get the age of a player with a complex last name.
```{python}
query = 'travis etienne jr. age'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get the names and ages of all of the wide receives on the Jacksonville Jaguars.
```{python}
query = 'jacksonville jaguars wide receiver name age'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get the names of all the wide receivers.
```{python}
query = 'name wide receiver'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get the ages of quarterbacks on the Jacksonville Jaguars.
```{python}
query = 'jaguars quarterback age'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get the college a player attended by last name.
```{python}
query = 'brown college'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get the college a player attended by full name.
```{python}
query = 'robert hainsey college'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get the age of a player by name.
```{python}
query = 'parker washington age'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get player years of experience
```{python}
query = 'trevor lawrence years of experience'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get player height inches measurement
It at least sometimes returns his height in feet and inches and in an awkward order.
```{python}
query = 'nick mullens height inches'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```

### Get player height feet measurement
```{python}
query = 'nick mullens height feet'
results = circuity.process_query(database, query)
merged_results_dictionary = {
                             key: [dict[key] for dict in results]
                             for key in results[0]
}
result_values_matrix = circuity.transpose_matrix(list(merged_results_dictionary.values()))
print(",".join(merged_results_dictionary.keys()))
for result_values_list in result_values_matrix:
    print(",".join(result_values_list))
```
