---
title: "Player database: importing and exporting data"
author: "Paul Billing-Ross"
date: "2025-09-18"
categories: [database, football, players]
---
# Introduction
Now that I have validated the basic search mechanism I want to establish a method for programmatically importing and exporting data to and from my database. Because I find loops to be an excellent validation method I want to make sure that I can import and export and then import the same data while retaining complete data fidelity.

My database is stored as [JSON](https://en.wikipedia.org/wiki/JSON) documents and while they are human readable they are not the easiest documents to manipulate manually. Comma separated values or "CSV" files are plain text and human readable and structured as tables which are more intuitive to look at. People who have used spreadsheets are probably already familiar with them.

I will created methods to import comma separated values files into the database and also to export the database as a set of comma separated files. Since the database files are stored in JSON, this effectively means that I will be convertint comma separated values files into JSON files.

I think I am going to start by implementing the export function because if I figure out how I want to export the data from my database then I can figure out what I expect the comma separated files to look like when I import them.

A challenge with exporting my database is that all of my files except for the index store metadata and only the index stores data. I will need to map the metadata to the data before I can export them.

## How do I want to structure my comma separated values files?
I currently store all of my database files in a `database` directory. At the root of this directory is an `index.json` file which contains all of the words in my database as well as a series of directories which represent all of the loops in my database. Currently I only have one loop which I am calling `player` because it contains football player references.

```
# Example directory and file structure of my database
database/
database/index.json
database/player
database/player/first-name.json
database/player/last-name.json
database/player/position.json
database/player/age.json
```

I am thinking that I want to create a single comma separated values file for each loop. Here is an example of how I could represent the database in a comma separated values table named `player`.

| first-name | last-name | position | age |
| --- | --- | --- | --- |
| Justin | Blackmon | free safety | 27 |
| Jarrian | Jones | cornerback | 23 |

## Thinking about importing
Now that I think about it a little the structure of the data I want to import and export is pretty straightforward. I am feeling a little stuck on how to represent the database in JSON to match what I want to do with exporting so now I am going to think about it from the other side - how do I want to handle import?

I want to provide a comma separated values file.
```
transform_csv_to_circuity_json("players.csv")
```

## Generating summary statistics at import
What does the `transform_csv_to_circuity_json()` function do? I am going to read the comma separated values into a matrix which will be row based because that is how Python natively reads files. Then I will convert it to a columnar matrix by transposing the values. And before importing the data I will want to do data validation and generate summary statistics. For the instance of the `age` column of the `player.csv` I would create an `age.json` database file with all of the values and then an `age.statistics.json` file with summary statistics. Every time I update the `age.json` file I recalculate and update the `age.statistics.json` file as well.

Because age is a numerical value I do not to transform those values. For the sake of writing the `age.json` file all I need to do is transform the name of the column `age` to the corresponding index reference. In order to do that I need to know where the word `age` is located in the `index_list`. In order to find the `age` entry I need to use the `index_dict`. You may be able to infer from their names that these variables contain different data structures. The first contains a list and the second contains a dictionary.

One way that I could lookup the index of the word `age` is by iterating through the `index_list` item by item and reading the `word` value of each dictionary item until I find "age". This could be an arbitrarily long process because I do not know where in the list I will find it.

## How do I populate the index?
That bring me to the question of how I am going to populate the index in the first place. When I create the index it will a list of a single dictionary referencing itself.

```
index_list = [{"word": "index", "index": 0, "references": [{"source": "database/index.json", "index": 0}]}]
word_references = {"index": [{"source": "database/index.json", "index": 0}]}
word_indexes = {"index": 0}
```

I read each word of the comma separated values file and I try to `get()` it from `word_references`. If it is not in the dictionary then I can add it to `index_list` and `word_references` and `word_indexes`. I can specify the outer `index` value based on the current length of the list.

How do I do that?
```
for item in column:
    word_indexes = []
    words = header.split(" ")
    for word in words:
        word_reference = word_references.get(word)
        if word_reference:
            word_index = word_indexes[word]
            word_indexes.append(word_index)
        else:
            # Add a new word entry to the database
            word_indexes[word] = [{"source":         

current_file = "whatever_this_file_is_named.json"
current_row = 7
new_word = "banana"
new_word_index = len(index_list)

new_word_entry = {"word": new_word, "index": new_word_index, "references": [{"source": current_file, "index": current_row}]}
index_list.append(new_word_entry)

word_references[new_word] = [{"source": current_file, "index": current_row}]
word_indexes[new_word] = new_word_index
```

## Workflow
- [x] Load the `players.csv` as a matrix of rows
- [x] Transpose the matrix of rows into a matrix of columns
- [x] Convert the actual values in each column into metadata values
- [ ] Add references to the next file to the end of each column
- [ ] Write the metadata columns to JSON files
- [ ] Convert the metadata columns back to data columns
- [ ] Write the data columns to a new comma separated values file


# Methods

## Load dependencies
```{python}
#| code-fold: true

# Manipulate files
import os
# Read comma separated values file
import csv
# Manipulate the database structures
import json
```

## Functions
```{python}
#| code-fold: true
def transpose_matrix(matrix):
    """Transpose a matrix represented as a list of lists.

    Arguments:
        matrix (list): A list of equal length lists.
    
    Returns:
        (list): A list of lists where all of the values have been transposed.
    """

    transposed_matrix = [[row[index] for row in row_matrix] for index in range(len(row_matrix[0]))]
    return transposed_matrix
```

```{python}
#| code-fold: true
def initialize_database():
    """Create the index variables the core of the database.
    
    Returns:
        (list): The primary index of words in the database stored as dictionaries with references to each location of each word in the database.
        (dict): A mapping of each word to all of its references.
        (dict): A mapping of each word to its position in the primary index.
    """

    index_list = [{"word": "index", "references": [{"source": "database/index.json", "index": 0}]}]
    word_references = {"index": [{"source": "index", "index": 0}]}
    word_indexes = {"index": 0}
    return index_list, word_references, word_indexes
```

```{python}
#| code-fold: true
def create_database_file(loop_name, data_column, index_list, word_references, word_indexes):
    """Create a database file from a column of data.

    Arguments:
        loop_name (str): The name of the input column.
        data_column (list): The data column.

    Returns:
        (list): Metadata references to each item in the input column.
    """
    # Create a list to store metadata references
    metadata_column = []

    # Name the new file to be created
    this_file_name = f"database/{loop_name}/{data_column[0]}.json"
    
    # Convert data values to metadata values 
    for column_index, item in enumerate(data_column):
        this_word_indexes = []
        words = item.split(" ")
        for word in words:
            this_word_reference = word_references.get(word)
            if this_word_reference:
                # If the word already exists in the database then I simply need to get the position of it in the primary index.
                word_index = word_indexes[word]
                this_word_indexes.append(word_index)
            else:
                # Add a new word entry to the database
                word_references[word] = [{"source": "database/index.json", "index": column_index}]
                word_index = len(index_list)
                word_indexes[word] = word_index
                index_list.append({"word": word, "references": [{"source": this_file_name, "index": column_index}]})
                this_word_indexes.append(word_index)
        this_word_reference = {"source": "database/index.json", "indexes": this_word_indexes}
        metadata_column.append(this_word_reference)

        # Add reference to the next at the end of each metadata column
        #next_column_index = column_index + 1
        #if next_column_index >= len(data_column):
        #    next_column_index = 0
        #next_column_name = data_column[next_column_index][0]
        #next_file_name = f"database/{loop_name}/{next_column_name}.json"
        #metadata_column.append(next_file_name)

    return metadata_column
```

```{python}
#| code-fold: true
def convert_comma_separated_values_file_to_matrix(csv_file):
    # Read file into a matrix of rows
    row_matrix = []
    with open(csv_file) as csv_handle:
        csv_reader = csv.reader(csv_handle)
        for row in csv_reader:
            row_matrix.append(row)
    
    # Convert the matrix of rows to columns
    column_matrix = [[row[index] for row in row_matrix] for index in range(len(row_matrix[0]))]
    return column_matrix
```

```{python}
def convert_data_matrix_to_metadata_matrix(data_matrix, index_list, word_references, word_indexes):
    metadata_columns = []
    for column in data_matrix:
        metadata_column = []
        column_name = column[0]

        for row_index, value in enumerate(column):
            reference = convert_string_to_reference(value, column_name, row_index, index_list, word_references, word_indexes)
            metadata_column.append(reference)
        metadata_columns.append(metadata_column)
    return metadata_columns
```    

```{python}
def convert_metadata_matrix_to_dictionary(metadata_matrix, index_list):
    dictionary_keys = [convert_reference_to_string(references[0], index_list) for references in metadata_matrix]
    metadata_dictionary = dict(zip(dictionary_keys, metadata_matrix))
    return metadata_dictionary
```    

```{python}
#| code-fold: true
def import_comma_separated_values(csv_file, index_list, word_references, word_indexes):
    """Import values from a comma separated values file into the database.

    Arguments:
        csv_file (str): The path to a comma separated values file.
        index_list (list): The primary database index.
        word_references (dict): Mapping of each word to its database locations.
        word_indexes (dict): Mapping of each word to its position in the primary index.

    Returns:
        index_list: Updated with new word locations.
        word_references: Updated with new words.
        word_indexes: Updated with new indexes.
    """
    loop_name = csv_file.split('/')[-1].split('.')[0]
    
    # Read file into a matrix of rows
    row_matrix = []
    with open(csv_file) as csv_handle:
        csv_reader = csv.reader(csv_handle)
        for row in csv_reader:
            row_matrix.append(row)
    
    # Convert the matrix of rows to columns
    column_matrix = [[row[index] for row in row_matrix] for index in range(len(row_matrix[0]))]

    # Convert the actual column values to references to the primary index
    metadata_columns = []
    for column in column_matrix:
        metadata_column = []
        #metadata_column = create_database_file(loop_name, column, index_list, word_references, word_indexes)
        for row_index, value in enumerate(column):
            reference = convert_string_to_reference(value, csv_file, row_index, index_list, word_references, word_indexes)
            metadata_column.append(reference)
        metadata_columns.append(metadata_column)

    # Write metadata columns to files
    for column in metadata_columns:
        print(column)
        basename = convert_reference_to_string(column[0], index_list)
        basename_list = [character.replace(' ', '-') for character in basename]
        new_basename = ''.join(basename_list)
        file_name = f"{new_basename}.json" 
        file_path = f"database/{loop_name}/{file_name}"
    
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, 'w') as file_handle:
            json.dump(column, file_handle)
    return metadata_columns
```

```{python}
def convert_reference_to_string(reference, index_list):
    #print(f"Converting reference '{reference}' to string.")
    if not isinstance(reference, dict):
        # Numbers stored in metadata files can be returned as is.
        return reference
    
    indexes = reference["indexes"]
    #word_dicts = [index_list[index] for index in indexes]


    words = [convert_index_to_word(index, index_list) for index in indexes]
    
    #words = [word_dict["word"] for word_dict in word_dicts]
    this_string = (" ").join(words)
    #print(f"Converted reference {reference} to string {this_string}.")
    return this_string
```

```{python}
def convert_index_to_word(index, index_list):
    #print(f"Converting index ({index}) to word.")
    # The word_dict contains the value of the word as other metadata.
    word_dict = index_list[index]
    word = word_dict["word"]
    #print(f"Converted index ({index}) to word {word}.")
    return word
```

```{python}
def convert_string_to_reference(string, this_file_name, row_index, index_list, word_references, word_indexes):
    #print(f"Converting string '{string}' to reference.")
    # All values can be stored as strings. In order to determine whether
    # a value contains words or numbers I am going to try converting it
    # to a float which is a numeric type. If I can convert it to a 
    # number then I will ignore it.
    try:
        number = float(string)
        return number
    except:
        this_string_indexes = []
        words = string.split(" ")
       
        conversion_dictionary = {
                                  "this_file_name": this_file_name,
                                  "row_index": row_index,
                                  "index_list": index_list,
                                  "word_references": word_references,
                                  "word_indexes": word_indexes
        }  
        this_string_indexes = [convert_word_to_index(word, **conversion_dictionary) for word in words] 
        this_string_reference = {
                                 "source": "database/index.json",
                                 "indexes": this_string_indexes
        }
        #print(f"Converted string '{string}' to reference {this_string_reference}.")
        return this_string_reference
```

```{python}
def convert_word_to_index(word, row_index, this_file_name, index_list, word_references, word_indexes):
    #print(f"Converting word '{word}' to index.")
    if not isinstance(word, str):
        # I want to convert words to references and leave numbers as they are
        return ValueError(f"This word is not of type string: {word}.")
    
    this_word_reference = word_references.get(word)
    if this_word_reference:
        # If the word already exists in the database then get the 
        # position of it in the primary index.
        word_index = word_indexes.get(word)
        if not word_index:
            return ValueError(f"Word '{word}' was not found in word_indexes: {word_indexes}.")
    else:
        # If the word does not yet exist in the database then
        # add a new word entry to the database
        word_references[word] = [{"source": "database/index.json", "index": row_index}]
        word_index = len(index_list)
        word_indexes[word] = word_index
        index_list.append({
                           "word": word,
                           "references": [{
                                           "source": this_file_name,
                                           "index": row_index
                                          }]
                          })
    #print(f"Converted word '{word}' to index {word_index}.")
    return word_index
```

## Initialize database
```{python}
index_list, word_references, word_indexes = initialize_database()
print(f"index_list: {index_list}, word_references: {word_references}, word_indexes: {word_indexes}.")
```

## Convert comma separated values file to data matrix
```{python}
csv_file = "players.csv"
data_matrix = convert_comma_separated_values_file_to_matrix(csv_file)
data_matrix
```

## Convert data matrix to metadata matrix
```{python}
metadata_matrix = convert_data_matrix_to_metadata_matrix(data_matrix, index_list, word_references, word_indexes)
metadata_matrix
```

## Convert data matrix to metadata matrix
```{python}
#index_list, word_references, word_indexes = initialize_database()
#csv_file = "players.csv"
#metadata_column_matrix = import_comma_separated_values(csv_file, index_list, word_references, word_indexes)
#metadata_column_matrix
```

## Convert metadata matrix back to data matrix
In order to validate my `import_comma_separated_values()` function I also want to transform the metadata values back into data values.
```{python}
reconstituted_data_matrix = [[convert_reference_to_string(reference, index_list) for reference in column] for column in metadata_matrix]
reconstituted_data_matrix
```

## Look at the state of the primary index
```{python}
index_list
```

## Convert the metadata matrix to a dictionary
```{python}
metadata_dictionary = convert_metadata_matrix_to_dictionary(metadata_matrix, index_list)
metadata_dictionary
```

Before I worry about serializing the database according to this new structure I want to make sure that my query logic still works.
      
## Write the database to files
```{python}
```

## Test the `create_database_file()` function
```{python}
metadata_column = create_database_file("test", ["name", "justin", "jarrian"], index_list, word_references, word_indexes)
metadata_column
```
